### ISSUE TITLE
Submission queries

### ISSUE THREAD

**Issue by Lootyhoof** [ThosRTanner/openlinkoverlay#10]
I see you submitted this add-on to the Add-ons Site(s). Great! But, it looks like it's all still credited to the old author. Phoebus parses the `em:creator` and `em:homepageURL` to add to the listing. If you are forking it, these should be your own. You're free to credit the original author either in the listing itself or somewhere else, but the creator and homepage should be relevant to **this** add-on, not another one. The original creator could be instead set as a `developer` or `contributor`, for example. Ideally, too, it would have a DIFFERENT name altogether as it's a fork (we stomped down on new submissions using the "Moon Edition" / "for Pale Moon" or similar styling suffixes to names a while ago).

Another (small) note, v29 is around the corner, it's probably best to include it as the `maxVersion` if you're able to confirm it works in the unstable builds.

Thanks for your understanding.

**Comment by ThosRTanner** [comment]
Done with latest release
